version: '3'

services:
  web:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - LDAP_HOST=10.0.100.11
      - PORT=8080
      - LDAP_USER=Administrator
      - LDAP_PASSWORD=oMu37Ta54Zwk
      - LDAP_DN=dc=killer,dc=be
      - LDAP_DOMAIN=killerbee.com

